version = 1

test_patterns = [
  'tests/**'
]

exclude_patterns = [
  'example/**'
]

[[analyzers]]
name = 'python'
enabled = true
runtime_version = '2.x.x'

  [analyzers.meta]
  max_line_length = 200

# Test coverage analyzer
[[analyzers]]
name = "test-coverage"
enabled = true
